### ISSUE TITLE
Elastic boundaries

### ISSUE THREAD

**Issue by mojtabaAmiraslanpour** [ChenguangZhang/sdfibm#3]
Does this also include moving boundaries or only solid body motion? As I can recall, there are no open-source codes dealing with moving boundaries using IB method in OpenFOAM. Can you work on that?

**Comment by ChenguangZhang** [comment]
@mojtabaAmiraslanpour Sorry for the late reply, not familiar with github yet. sdfibm only has rigid body motions, no elastic deformation. I think you are right that there is no elastic ibm in OpenFOAM, but I don't have recent plans to implement that because it's not related with my research.
