### ISSUE TITLE
Error during compilation

### ISSUE THREAD

**Issue by rudhkul** [ChenguangZhang/sdfibm#4]
I have installed OpenFOAM and the latest version of g++. I followed these commands:
`git clone https://github.com/ChenguangZhang/sdfibm.git
cd sdfibm/src
make`

 I received the following errors:
In file included from motionfactory.cpp:36:0:
motion000000.h:12:19: error: ‘real’ does not name a type; did you mean ‘dreml’?
             const real& time,
                   ^~~~
                   dreml
motion000000.h:11:18: error: ‘virtual void sdfibm::Motion000000::constraint(const int&, Foam::vector&, Foam::vector&)’ marked ‘override’, but does not override
     virtual void constraint(
                  ^~~~~~~~~~
motion000000.h:23:37: error: ‘real’ does not name a type; did you mean ‘dreml’?
 void Motion000000::constraint(const real &time, vector &velocity, vector &omega)
                                     ^~~~
                                     dreml
In file included from motionfactory.cpp:38:0:
motion000100.h:12:19: error: ‘real’ does not name a type; did you mean ‘dreml’?
             const real& time,
                   ^~~~
                   dreml
motion000100.h:11:18: error: ‘virtual void sdfibm::Motion000100::constraint(const int&, Foam::vector&, Foam::vector&)’ marked ‘override’, but does not override
     virtual void constraint(
                  ^~~~~~~~~~
motion000100.h:23:37: error: ‘real’ does not name a type; did you mean ‘dreml’?
 void Motion000100::constraint(const real &time, vector &velocity, vector &omega)
                                     ^~~~
                                     dreml
In file included from motionfactory.cpp:40:0:
motion000010.h:12:19: error: ‘real’ does not name a type; did you mean ‘dreml’?
             const real& time,
                   ^~~~
                   dreml
motion000010.h:11:18: error: ‘virtual void sdfibm::Motion000010::constraint(const int&, Foam::vector&, Foam::vector&)’ marked ‘override’, but does not override
     virtual void constraint(
                  ^~~~~~~~~~
motion000010.h:23:37: error: ‘real’ does not name a type; did you mean ‘dreml’?
 void Motion000010::constraint(const real &time, vector &velocity, vector &omega)
                                     ^~~~
                                     dreml
In file included from motionfactory.cpp:42:0:
motion000001.h:12:19: error: ‘real’ does not name a type; did you mean ‘dreml’?
             const real& time,
                   ^~~~
                   dreml
motion000001.h:11:18: error: ‘virtual void sdfibm::Motion000001::constraint(const int&, Foam::vector&, Foam::vector&)’ marked ‘override’, but does not override
     virtual void constraint(
                  ^~~~~~~~~~
motion000001.h:23:37: error: ‘real’ does not name a type; did you mean ‘dreml’?
 void Motion000001::constraint(const real &time, vector &velocity, vector &omega)
                                     ^~~~
                                     dreml
In file included from motionfactory.cpp:44:0:
motion000111.h:12:19: error: ‘real’ does not name a type; did you mean ‘dreml’?
             const real& time,
                   ^~~~
                   dreml
motion000111.h:11:18: error: ‘virtual void sdfibm::Motion000111::constraint(const int&, Foam::vector&, Foam::vector&)’ marked ‘override’, but does not override
     virtual void constraint(
                  ^~~~~~~~~~
motion000111.h:23:37: error: ‘real’ does not name a type; did you mean ‘dreml’?
 void Motion000111::constraint(const real &time, vector &velocity, vector &omega)
                                     ^~~~
                                     dreml
In file included from motionfactory.cpp:46:0:
motion000002.h:12:19: error: ‘real’ does not name a type; did you mean ‘dreml’?
             const real& time,
                   ^~~~
                   dreml
motion000002.h:32:5: error: ‘real’ does not name a type; did you mean ‘dreml’?
     real m_period, m_omega; // m_omegaz is only the z component
     ^~~~
     dreml
motion000002.h:11:18: error: ‘virtual void sdfibm::Motion000002::constraint(const int&, Foam::vector&, Foam::vector&)’ marked ‘override’, but does not override
     virtual void constraint(
                  ^~~~~~~~~~
motion000002.h: In constructor ‘sdfibm::Motion000002::Motion000002(const Foam::dictionary&)’:
motion000002.h:20:13: error: ‘m_period’ was not declared in this scope
             m_period = Foam::readScalar(para.lookup("period"));
             ^~~~~~~~
motion000002.h:20:13: note: suggested alternative: ‘cuserid’
             m_period = Foam::readScalar(para.lookup("period"));
             ^~~~~~~~
             cuserid
motion000002.h:26:9: error: ‘m_omega’ was not declared in this scope
         m_omega = 2*M_PI/m_period;
         ^~~~~~~
motion000002.h:26:26: error: ‘m_period’ was not declared in this scope
         m_omega = 2*M_PI/m_period;
                          ^~~~~~~~
motion000002.h:26:26: note: suggested alternative: ‘cuserid’
         m_omega = 2*M_PI/m_period;
                          ^~~~~~~~
                          cuserid
motion000002.h: At global scope:
motion000002.h:35:37: error: ‘real’ does not name a type; did you mean ‘dreml’?
 void Motion000002::constraint(const real &time, vector &velocity, vector &omega)
                                     ^~~~
                                     dreml
motion000002.h: In member function ‘virtual void sdfibm::Motion000002::constraint(const int&, Foam::vector&, Foam::vector&)’:
motion000002.h:39:16: error: ‘m_omega’ was not declared in this scope
     omega[2] = m_omega;
                ^~~~~~~
motion000002.h:39:16: note: suggested alternative: ‘omega’
     omega[2] = m_omega;
                ^~~~~~~
                omega
In file included from motionfactory.cpp:48:0:
motion110002.h: At global scope:
motion110002.h:12:19: error: ‘real’ does not name a type; did you mean ‘dreml’?
             const real& time,
                   ^~~~
                   dreml
motion110002.h:32:5: error: ‘real’ does not name a type; did you mean ‘dreml’?
     real m_period, m_omega; // m_omegaz is only the z component
     ^~~~
     dreml
motion110002.h:11:18: error: ‘virtual void sdfibm::Motion110002::constraint(const int&, Foam::vector&, Foam::vector&)’ marked ‘override’, but does not override
     virtual void constraint(
                  ^~~~~~~~~~
motion110002.h: In constructor ‘sdfibm::Motion110002::Motion110002(const Foam::dictionary&)’:
motion110002.h:20:13: error: ‘m_period’ was not declared in this scope
             m_period = Foam::readScalar(para.lookup("period"));
             ^~~~~~~~
motion110002.h:20:13: note: suggested alternative: ‘cuserid’
             m_period = Foam::readScalar(para.lookup("period"));
             ^~~~~~~~
             cuserid
motion110002.h:26:9: error: ‘m_omega’ was not declared in this scope
         m_omega = 2*M_PI/m_period;
         ^~~~~~~
motion110002.h:26:26: error: ‘m_period’ was not declared in this scope
         m_omega = 2*M_PI/m_period;
                          ^~~~~~~~
motion110002.h:26:26: note: suggested alternative: ‘cuserid’
         m_omega = 2*M_PI/m_period;
                          ^~~~~~~~
                          cuserid
motion110002.h: At global scope:
motion110002.h:35:37: error: ‘real’ does not name a type; did you mean ‘dreml’?
 void Motion110002::constraint(const real &time, vector &velocity, vector &omega)
                                     ^~~~
                                     dreml
motion110002.h: In member function ‘virtual void sdfibm::Motion110002::constraint(const int&, Foam::vector&, Foam::vector&)’:
motion110002.h:39:16: error: ‘m_omega’ was not declared in this scope
     omega[2] = m_omega;
                ^~~~~~~
motion110002.h:39:16: note: suggested alternative: ‘omega’
     omega[2] = m_omega;
                ^~~~~~~
                omega
In file included from motionfactory.cpp:50:0:
motion111111.h: At global scope:
motion111111.h:12:19: error: ‘real’ does not name a type; did you mean ‘dreml’?
             const real& time,
                   ^~~~
                   dreml
motion111111.h:11:18: error: ‘virtual void sdfibm::Motion111111::constraint(const int&, Foam::vector&, Foam::vector&)’ marked ‘override’, but does not override
     virtual void constraint(
                  ^~~~~~~~~~
motion111111.h:23:37: error: ‘real’ does not name a type; did you mean ‘dreml’?
 void Motion111111::constraint(const real &time, vector &velocity, vector &omega)
                                     ^~~~
                                     dreml
In file included from motionfactory.cpp:52:0:
motion222000.h:12:19: error: ‘real’ does not name a type; did you mean ‘dreml’?
             const real& time,
                   ^~~~
                   dreml
motion222000.h:32:5: error: ‘real’ does not name a type; did you mean ‘dreml’?
     real m_u, m_v, m_w;
     ^~~~
     dreml
motion222000.h:11:18: error: ‘virtual void sdfibm::Motion222000::constraint(const int&, Foam::vector&, Foam::vector&)’ marked ‘override’, but does not override
     virtual void constraint(
                  ^~~~~~~~~~
motion222000.h: In constructor ‘sdfibm::Motion222000::Motion222000(const Foam::dictionary&)’:
motion222000.h:20:13: error: ‘m_u’ was not declared in this scope
             m_u = Foam::readScalar(para.lookup("u"));
             ^~~
motion222000.h:21:13: error: ‘m_v’ was not declared in this scope
             m_v = Foam::readScalar(para.lookup("v"));
             ^~~
motion222000.h:22:13: error: ‘m_w’ was not declared in this scope
             m_w = Foam::readScalar(para.lookup("w"));
             ^~~
motion222000.h: At global scope:
motion222000.h:35:37: error: ‘real’ does not name a type; did you mean ‘dreml’?
 void Motion222000::constraint(const real &time, vector &velocity, vector &omega)
                                     ^~~~
                                     dreml
motion222000.h: In member function ‘virtual void sdfibm::Motion222000::constraint(const int&, Foam::vector&, Foam::vector&)’:
motion222000.h:37:23: error: ‘m_u’ was not declared in this scope
     velocity = vector(m_u, m_v, m_w);
                       ^~~
motion222000.h:37:28: error: ‘m_v’ was not declared in this scope
     velocity = vector(m_u, m_v, m_w);
                            ^~~
motion222000.h:37:33: error: ‘m_w’ was not declared in this scope
     velocity = vector(m_u, m_v, m_w);
                                 ^~~
In file included from motionfactory.cpp:54:0:
motionsinedirectional.h: At global scope:
motionsinedirectional.h:12:19: error: ‘real’ does not name a type; did you mean ‘dreml’?
             const real& time,
                   ^~~~
                   dreml
motionsinedirectional.h:38:5: error: ‘real’ does not name a type; did you mean ‘dreml’?
     real m_amplitude, m_period;
     ^~~~
     dreml
motionsinedirectional.h:41:5: error: ‘real’ does not name a type; did you mean ‘dreml’?
     real m_omega;
     ^~~~
     dreml
motionsinedirectional.h:11:18: error: ‘virtual void sdfibm::MotionSineDirectional::constraint(const int&, Foam::vector&, Foam::vector&)’ marked ‘override’, but does not override
     virtual void constraint(
                  ^~~~~~~~~~
motionsinedirectional.h: In constructor ‘sdfibm::MotionSineDirectional::MotionSineDirectional(const Foam::dictionary&)’:
motionsinedirectional.h:20:13: error: ‘m_amplitude’ was not declared in this scope
             m_amplitude = Foam::readScalar(para.lookup("amplitude"));
             ^~~~~~~~~~~
motionsinedirectional.h:21:13: error: ‘m_period’ was not declared in this scope
             m_period    = Foam::readScalar(para.lookup("period"));
             ^~~~~~~~
motionsinedirectional.h:21:13: note: suggested alternative: ‘cuserid’
             m_period    = Foam::readScalar(para.lookup("period"));
             ^~~~~~~~
             cuserid
motionsinedirectional.h:22:13: error: ‘m_omega’ was not declared in this scope
             m_omega = 2*M_PI/m_period;
             ^~~~~~~
motionsinedirectional.h: At global scope:
motionsinedirectional.h:44:46: error: ‘real’ does not name a type; did you mean ‘dreml’?
 void MotionSineDirectional::constraint(const real &time, vector &velocity, vector &omega)
                                              ^~~~
                                              dreml
motionsinedirectional.h: In member function ‘virtual void sdfibm::MotionSineDirectional::constraint(const int&, Foam::vector&, Foam::vector&)’:
motionsinedirectional.h:46:16: error: ‘m_amplitude’ was not declared in this scope
     velocity = m_amplitude * m_omega * std::cos(m_omega* time)*m_direction;
                ^~~~~~~~~~~
motionsinedirectional.h:46:30: error: ‘m_omega’ was not declared in this scope
     velocity = m_amplitude * m_omega * std::cos(m_omega* time)*m_direction;
                              ^~~~~~~
motionsinedirectional.h:46:30: note: suggested alternative: ‘omega’
     velocity = m_amplitude * m_omega * std::cos(m_omega* time)*m_direction;
                              ^~~~~~~
                              omega
In file included from motionfactory.cpp:56:0:
motion001001.h: At global scope:
motion001001.h:12:19: error: ‘real’ does not name a type; did you mean ‘dreml’?
             const real& time,
                   ^~~~
                   dreml
motion001001.h:11:18: error: ‘virtual void sdfibm::Motion001001::constraint(const int&, Foam::vector&, Foam::vector&)’ marked ‘override’, but does not override
     virtual void constraint(
                  ^~~~~~~~~~
motion001001.h:23:37: error: ‘real’ does not name a type; did you mean ‘dreml’?
 void Motion001001::constraint(const real &time, vector &velocity, vector &omega)
                                     ^~~~
                                     dreml
In file included from motionfactory.cpp:58:0:
motion010010.h:12:19: error: ‘real’ does not name a type; did you mean ‘dreml’?
             const real& time,
                   ^~~~
                   dreml
motion010010.h:11:18: error: ‘virtual void sdfibm::Motion010010::constraint(const int&, Foam::vector&, Foam::vector&)’ marked ‘override’, but does not override
     virtual void constraint(
                  ^~~~~~~~~~
motion010010.h:23:37: error: ‘real’ does not name a type; did you mean ‘dreml’?
 void Motion010010::constraint(const real &time, vector &velocity, vector &omega)
                                     ^~~~
                                     dreml
In file included from motionfactory.cpp:60:0:
motion100100.h:12:19: error: ‘real’ does not name a type; did you mean ‘dreml’?
             const real& time,
                   ^~~~
                   dreml
motion100100.h:11:18: error: ‘virtual void sdfibm::Motion100100::constraint(const int&, Foam::vector&, Foam::vector&)’ marked ‘override’, but does not override
     virtual void constraint(
                  ^~~~~~~~~~
motion100100.h:23:37: error: ‘real’ does not name a type; did you mean ‘dreml’?
 void Motion100100::constraint(const real &time, vector &velocity, vector &omega)
                                     ^~~~
                                     dreml
In file included from motionfactory.cpp:62:0:
motion01mask.h:12:19: error: ‘real’ does not name a type; did you mean ‘dreml’?
             const real& time,
                   ^~~~
                   dreml
motion01mask.h:11:18: error: ‘virtual void sdfibm::Motion01Mask::constraint(const int&, Foam::vector&, Foam::vector&)’ marked ‘override’, but does not override
     virtual void constraint(
                  ^~~~~~~~~~
motion01mask.h:60:37: error: ‘real’ does not name a type; did you mean ‘dreml’?
 void Motion01Mask::constraint(const real &time, vector &velocity, vector &omega)
                                     ^~~~
                                     dreml
In file included from motionfactory.cpp:64:0:
motionrotor.h:12:19: error: ‘real’ does not name a type; did you mean ‘dreml’?
             const real& time,
                   ^~~~
                   dreml
motionrotor.h:35:5: error: ‘real’ does not name a type; did you mean ‘dreml’?
     real m_period, m_omega;
     ^~~~
     dreml
motionrotor.h:36:5: error: ‘real’ does not name a type; did you mean ‘dreml’?
     real m_radius, m_theta0;
     ^~~~
     dreml
motionrotor.h:37:5: error: ‘real’ does not name a type; did you mean ‘dreml’?
     real m_selfom;
     ^~~~
     dreml
motionrotor.h:11:18: error: ‘virtual void sdfibm::MotionRotor::constraint(const int&, Foam::vector&, Foam::vector&)’ marked ‘override’, but does not override
     virtual void constraint(
                  ^~~~~~~~~~
motionrotor.h: In constructor ‘sdfibm::MotionRotor::MotionRotor(const Foam::dictionary&)’:
motionrotor.h:20:13: error: ‘m_period’ was not declared in this scope
             m_period = Foam::readScalar(para.lookup("period"));
             ^~~~~~~~
motionrotor.h:20:13: note: suggested alternative: ‘cuserid’
             m_period = Foam::readScalar(para.lookup("period"));
             ^~~~~~~~
             cuserid
motionrotor.h:21:13: error: ‘m_radius’ was not declared in this scope
             m_radius = Foam::readScalar(para.lookup("radius"));
             ^~~~~~~~
motionrotor.h:22:13: error: ‘m_theta0’ was not declared in this scope
             m_theta0 = Foam::readScalar(para.lookup("theta0"));
             ^~~~~~~~
motionrotor.h:23:13: error: ‘m_selfom’ was not declared in this scope
             m_selfom = Foam::readScalar(para.lookup("selfom"));
             ^~~~~~~~
motionrotor.h:29:9: error: ‘m_omega’ was not declared in this scope
         m_omega = 2*M_PI/m_period;
         ^~~~~~~
motionrotor.h:29:26: error: ‘m_period’ was not declared in this scope
         m_omega = 2*M_PI/m_period;
                          ^~~~~~~~
motionrotor.h:29:26: note: suggested alternative: ‘cuserid’
         m_omega = 2*M_PI/m_period;
                          ^~~~~~~~
                          cuserid
motionrotor.h: At global scope:
motionrotor.h:40:36: error: ‘real’ does not name a type; did you mean ‘dreml’?
 void MotionRotor::constraint(const real &time, vector &velocity, vector &omega)
                                    ^~~~
                                    dreml
motionrotor.h: In member function ‘virtual void sdfibm::MotionRotor::constraint(const int&, Foam::vector&, Foam::vector&)’:
motionrotor.h:43:20: error: ‘m_radius’ was not declared in this scope
     velocity[0] = -m_radius*m_omega*std::sin(m_omega*time + m_theta0);
                    ^~~~~~~~
motionrotor.h:43:29: error: ‘m_omega’ was not declared in this scope
     velocity[0] = -m_radius*m_omega*std::sin(m_omega*time + m_theta0);
                             ^~~~~~~
motionrotor.h:43:29: note: suggested alternative: ‘omega’
     velocity[0] = -m_radius*m_omega*std::sin(m_omega*time + m_theta0);
                             ^~~~~~~
                             omega
motionrotor.h:43:61: error: ‘m_theta0’ was not declared in this scope
     velocity[0] = -m_radius*m_omega*std::sin(m_omega*time + m_theta0);
                                                             ^~~~~~~~
motionrotor.h:46:16: error: ‘m_selfom’ was not declared in this scope
     omega[2] = m_selfom;
                ^~~~~~~~
In file included from motionfactory.cpp:1:0:
imotion.h: In instantiation of ‘static sdfibm::IMotion* sdfibm::_creator<T>::create(const Foam::dictionary&) [with T = sdfibm::Motion000000]’:
motionfactory.cpp:37:1:   required from here
imotion.h:23:16: error: invalid new-expression of abstract class type ‘sdfibm::Motion000000’
         return new T(node);
                ^~~~~~~~~~~
In file included from motionfactory.cpp:36:0:
motion000000.h:7:7: note:   because the following virtual functions are pure within ‘sdfibm::Motion000000’:
 class Motion000000:public IMotion, _creator<Motion000000>
       ^~~~~~~~~~~~
In file included from motionfactory.cpp:1:0:
imotion.h:34:18: note: 	virtual void sdfibm::IMotion::constraint(const scalar&, Foam::vector&, Foam::vector&)
     virtual void constraint(const scalar& time, vector& velocity, vector& omega) = 0;
                  ^~~~~~~~~~
imotion.h: In instantiation of ‘static sdfibm::IMotion* sdfibm::_creator<T>::create(const Foam::dictionary&) [with T = sdfibm::Motion000100]’:
motionfactory.cpp:39:1:   required from here
imotion.h:23:16: error: invalid new-expression of abstract class type ‘sdfibm::Motion000100’
         return new T(node);
                ^~~~~~~~~~~
In file included from motionfactory.cpp:38:0:
motion000100.h:7:7: note:   because the following virtual functions are pure within ‘sdfibm::Motion000100’:
 class Motion000100:public IMotion, _creator<Motion000100>
       ^~~~~~~~~~~~
In file included from motionfactory.cpp:1:0:
imotion.h:34:18: note: 	virtual void sdfibm::IMotion::constraint(const scalar&, Foam::vector&, Foam::vector&)
     virtual void constraint(const scalar& time, vector& velocity, vector& omega) = 0;
                  ^~~~~~~~~~
imotion.h: In instantiation of ‘static sdfibm::IMotion* sdfibm::_creator<T>::create(const Foam::dictionary&) [with T = sdfibm::Motion000010]’:
motionfactory.cpp:41:1:   required from here
imotion.h:23:16: error: invalid new-expression of abstract class type ‘sdfibm::Motion000010’
         return new T(node);
                ^~~~~~~~~~~
In file included from motionfactory.cpp:40:0:
motion000010.h:7:7: note:   because the following virtual functions are pure within ‘sdfibm::Motion000010’:
 class Motion000010:public IMotion, _creator<Motion000010>
       ^~~~~~~~~~~~
In file included from motionfactory.cpp:1:0:
imotion.h:34:18: note: 	virtual void sdfibm::IMotion::constraint(const scalar&, Foam::vector&, Foam::vector&)
     virtual void constraint(const scalar& time, vector& velocity, vector& omega) = 0;
                  ^~~~~~~~~~
imotion.h: In instantiation of ‘static sdfibm::IMotion* sdfibm::_creator<T>::create(const Foam::dictionary&) [with T = sdfibm::Motion000001]’:
motionfactory.cpp:43:1:   required from here
imotion.h:23:16: error: invalid new-expression of abstract class type ‘sdfibm::Motion000001’
         return new T(node);
                ^~~~~~~~~~~
In file included from motionfactory.cpp:42:0:
motion000001.h:7:7: note:   because the following virtual functions are pure within ‘sdfibm::Motion000001’:
 class Motion000001:public IMotion, _creator<Motion000001>
       ^~~~~~~~~~~~
In file included from motionfactory.cpp:1:0:
imotion.h:34:18: note: 	virtual void sdfibm::IMotion::constraint(const scalar&, Foam::vector&, Foam::vector&)
     virtual void constraint(const scalar& time, vector& velocity, vector& omega) = 0;
                  ^~~~~~~~~~
imotion.h: In instantiation of ‘static sdfibm::IMotion* sdfibm::_creator<T>::create(const Foam::dictionary&) [with T = sdfibm::Motion000111]’:
motionfactory.cpp:45:1:   required from here
imotion.h:23:16: error: invalid new-expression of abstract class type ‘sdfibm::Motion000111’
         return new T(node);
                ^~~~~~~~~~~
In file included from motionfactory.cpp:44:0:
motion000111.h:7:7: note:   because the following virtual functions are pure within ‘sdfibm::Motion000111’:
 class Motion000111:public IMotion, _creator<Motion000111>
       ^~~~~~~~~~~~
In file included from motionfactory.cpp:1:0:
imotion.h:34:18: note: 	virtual void sdfibm::IMotion::constraint(const scalar&, Foam::vector&, Foam::vector&)
     virtual void constraint(const scalar& time, vector& velocity, vector& omega) = 0;
                  ^~~~~~~~~~
imotion.h: In instantiation of ‘static sdfibm::IMotion* sdfibm::_creator<T>::create(const Foam::dictionary&) [with T = sdfibm::Motion000002]’:
motionfactory.cpp:47:1:   required from here
imotion.h:23:16: error: invalid new-expression of abstract class type ‘sdfibm::Motion000002’
         return new T(node);
                ^~~~~~~~~~~
In file included from motionfactory.cpp:46:0:
motion000002.h:7:7: note:   because the following virtual functions are pure within ‘sdfibm::Motion000002’:
 class Motion000002:public IMotion, _creator<Motion000002>
       ^~~~~~~~~~~~
In file included from motionfactory.cpp:1:0:
imotion.h:34:18: note: 	virtual void sdfibm::IMotion::constraint(const scalar&, Foam::vector&, Foam::vector&)
     virtual void constraint(const scalar& time, vector& velocity, vector& omega) = 0;
                  ^~~~~~~~~~
imotion.h: In instantiation of ‘static sdfibm::IMotion* sdfibm::_creator<T>::create(const Foam::dictionary&) [with T = sdfibm::Motion110002]’:
motionfactory.cpp:49:1:   required from here
imotion.h:23:16: error: invalid new-expression of abstract class type ‘sdfibm::Motion110002’
         return new T(node);
                ^~~~~~~~~~~
In file included from motionfactory.cpp:48:0:
motion110002.h:7:7: note:   because the following virtual functions are pure within ‘sdfibm::Motion110002’:
 class Motion110002:public IMotion, _creator<Motion110002>
       ^~~~~~~~~~~~
In file included from motionfactory.cpp:1:0:
imotion.h:34:18: note: 	virtual void sdfibm::IMotion::constraint(const scalar&, Foam::vector&, Foam::vector&)
     virtual void constraint(const scalar& time, vector& velocity, vector& omega) = 0;
                  ^~~~~~~~~~
imotion.h: In instantiation of ‘static sdfibm::IMotion* sdfibm::_creator<T>::create(const Foam::dictionary&) [with T = sdfibm::Motion111111]’:
motionfactory.cpp:51:1:   required from here
imotion.h:23:16: error: invalid new-expression of abstract class type ‘sdfibm::Motion111111’
         return new T(node);
                ^~~~~~~~~~~
In file included from motionfactory.cpp:50:0:
motion111111.h:7:7: note:   because the following virtual functions are pure within ‘sdfibm::Motion111111’:
 class Motion111111:public IMotion, _creator<Motion111111>
       ^~~~~~~~~~~~
In file included from motionfactory.cpp:1:0:
imotion.h:34:18: note: 	virtual void sdfibm::IMotion::constraint(const scalar&, Foam::vector&, Foam::vector&)
     virtual void constraint(const scalar& time, vector& velocity, vector& omega) = 0;
                  ^~~~~~~~~~
imotion.h: In instantiation of ‘static sdfibm::IMotion* sdfibm::_creator<T>::create(const Foam::dictionary&) [with T = sdfibm::Motion222000]’:
motionfactory.cpp:53:1:   required from here
imotion.h:23:16: error: invalid new-expression of abstract class type ‘sdfibm::Motion222000’
         return new T(node);
                ^~~~~~~~~~~
In file included from motionfactory.cpp:52:0:
motion222000.h:7:7: note:   because the following virtual functions are pure within ‘sdfibm::Motion222000’:
 class Motion222000:public IMotion, _creator<Motion222000>
       ^~~~~~~~~~~~
In file included from motionfactory.cpp:1:0:
imotion.h:34:18: note: 	virtual void sdfibm::IMotion::constraint(const scalar&, Foam::vector&, Foam::vector&)
     virtual void constraint(const scalar& time, vector& velocity, vector& omega) = 0;
                  ^~~~~~~~~~
imotion.h: In instantiation of ‘static sdfibm::IMotion* sdfibm::_creator<T>::create(const Foam::dictionary&) [with T = sdfibm::MotionSineDirectional]’:
motionfactory.cpp:55:1:   required from here
imotion.h:23:16: error: invalid new-expression of abstract class type ‘sdfibm::MotionSineDirectional’
         return new T(node);
                ^~~~~~~~~~~
In file included from motionfactory.cpp:54:0:
motionsinedirectional.h:7:7: note:   because the following virtual functions are pure within ‘sdfibm::MotionSineDirectional’:
 class MotionSineDirectional:public IMotion, _creator<MotionSineDirectional>
       ^~~~~~~~~~~~~~~~~~~~~
In file included from motionfactory.cpp:1:0:
imotion.h:34:18: note: 	virtual void sdfibm::IMotion::constraint(const scalar&, Foam::vector&, Foam::vector&)
     virtual void constraint(const scalar& time, vector& velocity, vector& omega) = 0;
                  ^~~~~~~~~~
imotion.h: In instantiation of ‘static sdfibm::IMotion* sdfibm::_creator<T>::create(const Foam::dictionary&) [with T = sdfibm::Motion001001]’:
motionfactory.cpp:57:1:   required from here
imotion.h:23:16: error: invalid new-expression of abstract class type ‘sdfibm::Motion001001’
         return new T(node);
                ^~~~~~~~~~~
In file included from motionfactory.cpp:56:0:
motion001001.h:7:7: note:   because the following virtual functions are pure within ‘sdfibm::Motion001001’:
 class Motion001001:public IMotion, _creator<Motion001001>
       ^~~~~~~~~~~~
In file included from motionfactory.cpp:1:0:
imotion.h:34:18: note: 	virtual void sdfibm::IMotion::constraint(const scalar&, Foam::vector&, Foam::vector&)
     virtual void constraint(const scalar& time, vector& velocity, vector& omega) = 0;
                  ^~~~~~~~~~
imotion.h: In instantiation of ‘static sdfibm::IMotion* sdfibm::_creator<T>::create(const Foam::dictionary&) [with T = sdfibm::Motion010010]’:
motionfactory.cpp:59:1:   required from here
imotion.h:23:16: error: invalid new-expression of abstract class type ‘sdfibm::Motion010010’
         return new T(node);
                ^~~~~~~~~~~
In file included from motionfactory.cpp:58:0:
motion010010.h:7:7: note:   because the following virtual functions are pure within ‘sdfibm::Motion010010’:
 class Motion010010:public IMotion, _creator<Motion010010>
       ^~~~~~~~~~~~
In file included from motionfactory.cpp:1:0:
imotion.h:34:18: note: 	virtual void sdfibm::IMotion::constraint(const scalar&, Foam::vector&, Foam::vector&)
     virtual void constraint(const scalar& time, vector& velocity, vector& omega) = 0;
                  ^~~~~~~~~~
imotion.h: In instantiation of ‘static sdfibm::IMotion* sdfibm::_creator<T>::create(const Foam::dictionary&) [with T = sdfibm::Motion100100]’:
motionfactory.cpp:61:1:   required from here
imotion.h:23:16: error: invalid new-expression of abstract class type ‘sdfibm::Motion100100’
         return new T(node);
                ^~~~~~~~~~~
In file included from motionfactory.cpp:60:0:
motion100100.h:7:7: note:   because the following virtual functions are pure within ‘sdfibm::Motion100100’:
 class Motion100100:public IMotion, _creator<Motion100100>
       ^~~~~~~~~~~~
In file included from motionfactory.cpp:1:0:
imotion.h:34:18: note: 	virtual void sdfibm::IMotion::constraint(const scalar&, Foam::vector&, Foam::vector&)
     virtual void constraint(const scalar& time, vector& velocity, vector& omega) = 0;
                  ^~~~~~~~~~
imotion.h: In instantiation of ‘static sdfibm::IMotion* sdfibm::_creator<T>::create(const Foam::dictionary&) [with T = sdfibm::Motion01Mask]’:
motionfactory.cpp:63:1:   required from here
imotion.h:23:16: error: invalid new-expression of abstract class type ‘sdfibm::Motion01Mask’
         return new T(node);
                ^~~~~~~~~~~
In file included from motionfactory.cpp:62:0:
motion01mask.h:7:7: note:   because the following virtual functions are pure within ‘sdfibm::Motion01Mask’:
 class Motion01Mask:public IMotion, _creator<Motion01Mask>
       ^~~~~~~~~~~~
In file included from motionfactory.cpp:1:0:
imotion.h:34:18: note: 	virtual void sdfibm::IMotion::constraint(const scalar&, Foam::vector&, Foam::vector&)
     virtual void constraint(const scalar& time, vector& velocity, vector& omega) = 0;
                  ^~~~~~~~~~
imotion.h: In instantiation of ‘static sdfibm::IMotion* sdfibm::_creator<T>::create(const Foam::dictionary&) [with T = sdfibm::MotionRotor]’:
motionfactory.cpp:65:1:   required from here
imotion.h:23:16: error: invalid new-expression of abstract class type ‘sdfibm::MotionRotor’
         return new T(node);
                ^~~~~~~~~~~
In file included from motionfactory.cpp:64:0:
motionrotor.h:7:7: note:   because the following virtual functions are pure within ‘sdfibm::MotionRotor’:
 class MotionRotor:public IMotion, _creator<MotionRotor>
       ^~~~~~~~~~~
In file included from motionfactory.cpp:1:0:
imotion.h:34:18: note: 	virtual void sdfibm::IMotion::constraint(const scalar&, Foam::vector&, Foam::vector&)
     virtual void constraint(const scalar& time, vector& velocity, vector& omega) = 0;
                  ^~~~~~~~~~
Makefile:38: recipe for target 'motionfactory.o' failed
make[1]: *** [motionfactory.o] Error 1
make[1]: Leaving directory '/media/ani/B6DCF2DCDCF295B9/OPENFOAM_FUTURE/sdfibm/src/libmotion'
Makefile:46: recipe for target 'libmotion' failed
make: *** [libmotion] Error 2

Please help me out.

**Comment by ChenguangZhang** [comment]
Cause: the real type is redundant and replaced by scalar, but I missed updating those under libmotion.

Fixed.
