### ISSUE TITLE
Missing details in fvSchemes

### ISSUE THREAD

**Issue by rudhkul** [ChenguangZhang/sdfibm#5]
After compiling and trying to run examples, "keyword div(Fs) is undefined in the dictionary" error pops up.

Moreover, I think for running the cases swak4foam has to be installed. Hence, please add the details of the version that has to be installed in the Readme file.

--> FOAM Warning : 
    From function void* Foam::dlOpen(const Foam::fileName&, bool)
    in file POSIX.C at line 1234
    dlopen error : libgroovyBC.so: cannot open shared object file: No such file or directory
--> FOAM Warning : 
    From function bool Foam::dlLibraryTable::open(const Foam::fileName&, bool)
    in file db/dynamicLibrary/dlLibraryTable/dlLibraryTable.C at line 105
    could not load "libgroovyBC.so"

**Comment by ChenguangZhang** [comment]
@rudhkul Hi Rudhkul, thanks for the feedback. 
1. The div(Fs) scheme is added to all examples.
2. The line of libgroovyBC.so is removed from the taylor-couette flow case, it was useless. The code & case do not depend on swak4foam.
