### ISSUE TITLE
Cannot Run Smooth VOF Exmaple

### ISSUE THREAD

**Issue by rudhkul** [ChenguangZhang/sdfibm#6]
Thank you for resolving the earlier issues promptly.

I am trying to the smooth VOF in the example folder. I am getting the following error.

Create time

Create mesh for time = 0

* No field name provided, default to alpha.water
* Write smooth phase field ["alpha.water"] to ./0, total volume = 5.20182
* Finished at "20/08/30 15:29:24"

**Comment by ChenguangZhang** [comment]
Hi, that's not an error, it's the log of the executable. 
The field is successfully initialized, which can be checked by paraview etc.
